### PR TITLE
added solution to 3 programs 

### PR DESCRIPTION
**Pull request by shantamsultania**
1. Exactly 3 Divisiors
2. Kadanes Algo 
.3 wave array 

please look into this repo and also add this is hacktoberfest if possible 
@littleironical @laxmipandey47

### CODE REVIEW

**Comment by shantamsultania** [comment]
i hope all is ok and we can merge the code if no issues are there also if possible add the hacktoberfest accepted tag

**Review by laxmipandey47 — CHANGES_REQUESTED** [review]
It will be great if you take the input values from the user, so the program will be valid for any given inputs. Rest of the things are fine.

**Comment by shantamsultania** [comment]
will do the same

**Comment by shantamsultania** [comment]
hi @laxmipandey47 i am done with the requested changes please review once

**Review by laxmipandey47 — APPROVED** [review]

**Review by laxmipandey47 — APPROVED** [review]
Looks good to me!!

**Comment by shantamsultania** [comment]
just one thing can you also add a hacktoberfest accepted label this progress did not got visible in my profile
thanks

**Pull request merged**
